# Generated by Django 5.0.7 on 2024-07-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('old', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
    ]
