# Generated by Django 5.0.7 on 2024-07-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='aboutme',
            name='contact',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
